In [2]:
import numpy as np

In [2]:
my_data = np.genfromtxt('mcpd_augmented.csv', delimiter=',')

##### Index a column in numpy display(my_data[:,1])

In [41]:
## Needs to set up the standard Deviation and the Standard mean in row form...

mean_data = np.mean(my_data,axis=0)
std_data = np.std(my_data,axis=0)
std_data[std_data==0]=1

Z-Score = (value-mean)/std

In [42]:
z_scored_data = (my_data - mean_data) / std_data

## Activation Layers

In [35]:
def Linear(Layer):
    linear_data = Layer
    return linear_data
def ReLu(Layer):
    relu_data = np.maximum(0,Layer)
    return relu_data
def Sigmoid(Layer):
    sig_data = 1/(1+np.exp(-Layer))
    return sig_data
def Softmax(Layer):
    top, bottom = np.exp(Layer-(np.amax(Layer, axis=0))), np.sum(np.exp(Layer-(np.amax(Layer, axis=0))))
    soft_data = top/bottom
    return soft_data

# Either Tanh will work
def Tanh(Layer):
    pos = np.exp(Layer)
    neg = np.exp(-Layer)
    tanh_data = (pos-neg)/(pos+neg)
    return tanh_data
def Tanh2(Layer):
    tanh_data = (np.exp(Layer) - np.exp(-Layer)) / (np.exp(Layer)+np.exp(-Layer))
    return tanh_data


In [36]:
linear_data = Linear(z_scored_data)
relu_data = ReLu(z_scored_data)
sig_data = Sigmoid(z_scored_data)
soft_data = Softmax(z_scored_data)
tanh1_data = Tanh(z_scored_data)
tanh2_data = Tanh2(z_scored_data)


## Fully Connected Layer

Takes in the number of Features coming in and coming out. Weights should be random values in between -+10^-4
The two attributes are the weight matrx and the the bias vector

In [43]:
n,m = z_scored_data.shape

In [59]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [46]:
test = np.random.uniform(-0.0001, 0.0001,size=(6,2))
weight = np.matmul(z_scored_data,test)
bias = np.random.uniform(-0.0001, 0.0001,size=(1,2))

In [49]:
h  = np.array([[-1,2,3,4]])

In [7]:
empt_array = np.zeros((np.size(h),np.size(h)))

In [12]:
x = np.fill_diagonal(empt_array,np.ones(np.size(h)))
display(empt_array)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0, 2, 3, 4]])

In [50]:
h[h>=0]=1
display(h)
h[h<0]=0
display(h)

array([[-1,  1,  1,  1]])

array([[0, 1, 1, 1]])

In [22]:
empt_array = np.zeros((np.size(h),np.size(h)))
np.fill_diagonal(empt_array,h)
display(empt_array)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Sigmoid

In [52]:
h  = np.array([[1,2,3,4]])
h_forward = np.array([[0.73105858, 0.88079708, 0.95257413, 0.98201379]])

In [54]:
h_diag = h_forward*(1-h_forward) # this works
in_size = np.size(h_diag)

In [55]:
empt_array = np.zeros((in_size,in_size))
np.fill_diagonal(empt_array,h_diag)
display(empt_array)

array([[0.19661193, 0.        , 0.        , 0.        ],
       [0.        , 0.10499358, 0.        , 0.        ],
       [0.        , 0.        , 0.04517666, 0.        ],
       [0.        , 0.        , 0.        , 0.01766271]])

Tanh

In [56]:
h_forward = np.array([[0.76159416, 0.96402758, 0.99505475, 0.9993293 ]])

In [57]:
display(1-h_forward**2)

array([[0.41997434, 0.07065082, 0.00986604, 0.00134095]])

Softmax

In [65]:
h_for = np.array([[0.0320586,  0.08714432, 0.23688282, 0.64391426]])

In [68]:
print(h_for[:,1])

[0.08714432]


In [71]:
len(h_for[0])

4

In [72]:
for i in range(0,len(h_for[0])): # this works for location
    print(h_for[:,i])

[0.0320586]
[0.08714432]
[0.23688282]
[0.64391426]


In [74]:
empt_array = np.zeros((in_size,in_size)) #empty 4x4 matrix
np.fill_diagonal(empt_array,h_diag)
display(empt_array)

array([[0.19661193, 0.        , 0.        , 0.        ],
       [0.        , 0.10499358, 0.        , 0.        ],
       [0.        , 0.        , 0.04517666, 0.        ],
       [0.        , 0.        , 0.        , 0.01766271]])

In [76]:
for col in range(0,len(empt_array[0])):
    for row in range(0,len(empt_array)):
        print(empt_array[row,col],col)

0.19661193260838358 0
0.0 0
0.0 0
0.0 0
0.0 1
0.10499358386347359 1
0.0 1
0.0 1
0.0 2
0.0 2
0.045176656854743084 2
0.0 2
0.0 3
0.0 3
0.0 3
0.017662706249835902 3


In [84]:
ar_index = 0
while ar_index < len(h_for[0]):
    for mat_index in range(0,len(empt_array)):
        if mat_index == ar_index:
            empt_array[mat_index,ar_index] = h_for[:,ar_index]*(1-h_for[:,ar_index])
        else:
            empt_array[mat_index,ar_index] = -h_for[:,ar_index] * h_for[:,mat_index]
    ar_index+=1


In [85]:
empt_array

array([[ 0.03103085, -0.00279372, -0.00759413, -0.02064299],
       [-0.00279372,  0.07955019, -0.02064299, -0.05611347],
       [-0.00759413, -0.02064299,  0.18076935, -0.15253223],
       [-0.02064299, -0.05611347, -0.15253223,  0.22928869]])

In [86]:
np.transpose(empt_array)

array([[ 0.03103085, -0.00279372, -0.00759413, -0.02064299],
       [-0.00279372,  0.07955019, -0.02064299, -0.05611347],
       [-0.00759413, -0.02064299,  0.18076935, -0.15253223],
       [-0.02064299, -0.05611347, -0.15253223,  0.22928869]])